### ISSUE TITLE
Module 4 Unit 4

### ISSUE THREAD

**Issue by azharkhuwaja** [MicrosoftLearning/AZ-700-Designing-and-Implementing-Microsoft-Azure-Networking-Solutions#133]
# Module: 04
#### Step: 03

Description of issue: Step 3 says "Deploy the following ARM templates to create the **virtual network, subnets**, and VMs needed for this exercise:"

Correction: Virtual networks and subnets are already created in task 1 therefore the correct statement should be "Deploy the following ARM templates to create VMs needed for this exercise:"

**Comment by jileary23** [comment]
Thank you for the feedback. This has been updated.
