### ISSUE TITLE
JSON Deployment Fails

### ISSUE THREAD

**Issue by AMorin8787** [MicrosoftLearning/AZ-700-Designing-and-Implementing-Microsoft-Azure-Networking-Solutions#135]
# Module: 02 Unit 03 Create and configure a virtual network gateway
#### Step 3: Deploy the following ARM templates to create the VMs needed for this exercise:

Description of issue: When trying to deploy the ARM template to create the VM's required by the lab, an error is output in the Cloud Shell saying the deployment failed with errors.

Status Message: The template deployment failed with error: 'The resource with id [ManufacturingVM] failed validation with message: 'The requested size for resource [ManufacturingVM] is currently not available in location 'West Europe' zones'

**Comment by jileary23** [comment]
Thank you for the feedback. Was this deployment on an Azure Pass subscription?

**Comment by AMorin8787** [comment]
Yes it was.

**Comment by jileary23** [comment]
This has been noted as an issue and is due to Azure Pass not the ARM templates.

**Comment by AMorin8787** [comment]
Is there an alternative method recommended to avoid these errors?
