### ISSUE TITLE
M05 unit 6

### ISSUE THREAD

**Issue by TommyKobber** [MicrosoftLearning/AZ-700-Designing-and-Implementing-Microsoft-Azure-Networking-Solutions#136]
# Module: 05
#### Step: 01- 3

Deployment of Front Door has changed. Either the whole lab should be rewritten for the new deployment, or the student should choose "front door and DN Profiles", then "Explore other offerings" and then click continue to choose Azure Front Door Classic

Repro steps:

1.
1.
1.

**Comment by MOC-Labs-Review** [comment]
MOC Labs Review has solved this issue with pull request #147.
