### ISSUE TITLE
M05-Unit 4 Deploy Azure Application Gateway - The 'Priority' option is not shown in the lab / the image should be updated

### ISSUE THREAD

**Issue by daveRendon** [MicrosoftLearning/AZ-700-Designing-and-Implementing-Microsoft-Azure-Networking-Solutions#155]
![appgtwy](https://user-images.githubusercontent.com/1934250/166722177-10322b31-82d4-4ef0-8f61-0d8139a1ad29.png)
# Module: M05-Unit 4 Deploy Azure Application Gateway
#### Step: 19

Description of issue

Repro steps:

1. Step 19, when configuring the routing rule, there's a new option called 'Priority'. The lab needs to reflect this update as this is a required field.
1.
1.

**Comment by MOC-Labs-Review** [comment]
MOC Labs Review has solved this issue with pull request #161.
