### ISSUE TITLE
New-AzPrivateDnsZoneConfig **is not recognized**

### ISSUE THREAD

**Issue by chrzanowskiItta** [MicrosoftLearning/AZ-700-Designing-and-Implementing-Microsoft-Azure-Networking-Solutions#156]
[# Module: 07

Hello
in the step private dns zone 

the command New-AzPrivateDnsZoneConfig **is not recognized**
so cannot run the script !!!

thanks

**Comment by MOC-Labs-Review** [comment]
MOC Labs Review did not experience this issue.

**Comment by jileary23** [comment]
Please insure you have Installed the Az PowerShell module
