### ISSUE TITLE
M01 - Issues deploying VM in Powershell CLI

### ISSUE THREAD

**Issue by wastedyears1981** [MicrosoftLearning/AZ-700-Designing-and-Implementing-Microsoft-Azure-Networking-Solutions#162]
Currently working through the Azure Network Engineer labs and having issues deploying the VMs for M01 - Exercise: Configure domain name servers settings in Azure.

After uploading azuredeploy.json and azuredeploy.parameters.json into the Cloud Shell home directory, running New-AzResourceGroupDeployment -ResourceGroupName $RGName -TemplateFile azuredeploy.json -TemplateParameterFile azuredeploy.parameters.json fails.

Issue Requested size for resource is currently not available in location 'eastus' zones.

Does anyone know a work-around.

**Comment by netslapper** [comment]
I am getting the same issue, I was looking at the restrictions in the sub list and I didn't see anything that was obvious to me that it should unavailable. 

Anyone able to find a solution or update to the .json to fix this? Thanks in advanced!

**Comment by netslapper** [comment]
I am having similar issue with ManufacturingVMazuredeploy.json and ManufacturingVMazuredeploy.parameters.json in M01. Showing that 'West Europe' is not available. 

Running commands to view restrictions on the sub list didn't show anything obvious.. at least to me. Is there a known issue to where the json file needs an update?

Thanks in advanced!

**Comment by netslapper** [comment]
Got it to work, looks like some of the locations are having issues, just edit the json file with a different location and save. Reupload the 2 files separately then you should be able to finish the exercises.

**Comment by FMartull** [comment]
> Got it to work, looks like some of the locations are having issues, just edit the json file with a different location and save. Reupload the 2 files separately then you should be able to finish the exercises.

Thanks for the tip @netslapper 

It worked with eastus in my case.

I have France Central as RG location
I edited in the CludShell the json file and replaced _[resourceGroup().location]_ with _northeurope_ and it failed with the same error I got before, regarding the missing Network Interface:

```
Status Message: Resource /subscriptions/***/resourceGroups/rg-az700/providers/Microsoft.Network/virtualNetworks/CoreServicesVnet/subnets/DatabaseSubnet referenced by resource /subscriptions/***/resourceGroups/rg-az700/providers/Microsoft.Network/networkInterfaces/testvm2-nic was not found. Please make sure that the referenced resource exists, and that both resources are in the same region. (Code: InvalidResourceReference)
```

The RG has three vNets, being _DatabaseSubnet_ where the Network Interfaces are connected in the CoreServicesVnet, which exists in **eastus**
