### ISSUE TITLE
error when deploying in cloud shell

### ISSUE THREAD

**Issue by raresmftie** [MicrosoftLearning/AZ-700-Designing-and-Implementing-Microsoft-Azure-Networking-Solutions#184]
# Module: 06
#### Step: 00

Description of issue

https://learn.microsoft.com/en-us/training/modules/introduction-to-azure-virtual-networks/6-exercise-configure-domain-name-servers-configuration-azure
Task 3: Create Virtual Machines to test the configuration

when using the command

New-AzResourceGroupDeployment -ResourceGroupName $RGName -TemplateFile azuredeploy.json -TemplateParameterFile azuredeploy.parameters.json

an error is returned

![WhatsApp Image 2022-09-23 at 21 20 22](https://user-images.githubusercontent.com/114256875/192038312-19f825ec-8a8b-4a70-b49b-789f952fc72a.jpeg)

**Comment by jileary23** [comment]
When following the exercise instructions this error could not be replicated - please ensure that all steps are followed to complete the exercise successfully.
