### ISSUE TITLE
M02 Unit 7 Hub routing preference

### ISSUE THREAD

**Issue by athelen20** [MicrosoftLearning/AZ-700-Designing-and-Implementing-Microsoft-Azure-Networking-Solutions#198]
# Module: 02
#### Step: 04

Description of issue
Missing the configuration information for "Hub routing preference"

Repro steps:
Must select ExpressRoute, VPN or AS Path.

**Comment by jileary23** [comment]
This field is only available as part of the virtual hub routing preference preview and can only be viewed in the preview portal.
