### ISSUE TITLE
M04-Unit 6 - Monitoring defaults to use http (port 80)

### ISSUE THREAD

**Issue by mct370770** [MicrosoftLearning/AZ-700-Designing-and-Implementing-Microsoft-Azure-Networking-Solutions#201]
# Module: 04
#### Step: 07

Description of issue
The Monitor Status will remain as "Degraded"
Because til monitor setting will use http (port 80) and webapps nowadays will not have port 80 enabled by default.

Repair steps:
Change configuration of Endpoint monitor setting to use https (port 443)

![1](https://user-images.githubusercontent.com/50733331/220457226-479864b1-84bc-47a3-9aa6-9baa68551dc3.png)
![2](https://user-images.githubusercontent.com/50733331/220457229-c4246df2-232d-4223-891d-2e13e8177b3c.png)
![3](https://user-images.githubusercontent.com/50733331/220457232-25234901-e88d-4fbf-b4f6-031c98760661.png)
![4](https://user-images.githubusercontent.com/50733331/220457235-ce66f282-8f9f-4c03-8e1f-66318a091f73.png)

**Comment by jileary23** [comment]
This has been added to the lab. Thank you.
