### ISSUE TITLE
Missing Image on M01, Uni6, Step4

### ISSUE THREAD

**Issue by eestevao** [MicrosoftLearning/AZ-700-Designing-and-Implementing-Microsoft-Azure-Networking-Solutions#202]
# Module: 01
#### Step: 03

Description of issue
In the 1st lab task 4, step 3, it shows the [T] to copy/paste to the lab for a note, so students are copying this and expecting a result instead of just doing what's there. I think we need to replace that to something easier to follow or at least remove the [T]

Both, step 3 under, first under task 4 and the next step (called "connect to the Test VMs using RDP") have the same issue. There is a .png image that was supposed to be present instead.

Repro steps:

1.
1.
1.

**Comment by jileary23** [comment]
[T] Copy/paste is unique to lab hosters. This feedback has been shared with the lab hoster Skillable.
