### ISSUE TITLE
M02-Unit 3 Create and configure a virtual network gateway - need to change to STANDARD SKU for Public IP

### ISSUE THREAD

**Issue by mkennten** [MicrosoftLearning/AZ-700-Designing-and-Implementing-Microsoft-Azure-Networking-Solutions#204]
# Module: 02
#### Step: 03

Instruction tells us to select BASIC SKU for the VpnGw1 but only STANDARD is supported - BASIC cannot be selected (anymore?). The deployment still works, instructions need to be updated.

![image](https://user-images.githubusercontent.com/37703728/224077304-dc9b5137-2ac6-4333-a987-e0b0448bb872.png)

**Comment by jileary23** [comment]
Thank you this has been fixed.
