### ISSUE TITLE
lab 8 task 3

### ISSUE THREAD

**Issue by Universo-Ap00** [MicrosoftLearning/AZ-700-Designing-and-Implementing-Microsoft-Azure-Networking-Solutions#207]
#### Step: 03

Description of issue:
- There is no 'Associated to" sections. backend creation configuration showing us in instructions they want associated to VMs but only NIC or IP options show. 

![image](https://user-images.githubusercontent.com/53233868/226399055-78da55dc-c586-40bd-a20e-8f1a6f820d4d.png)

Repro steps:

1. re-write to match UI, Can add IP to associate each VM.
2. under IP configurations, add --> select the VMs (3) and they provide the IPs of the VMs

**Comment by jileary23** [comment]
This has been updated
