### ISSUE TITLE
Lab 8 - UI changes not reflected

### ISSUE THREAD

**Issue by mkennten** [MicrosoftLearning/AZ-700-Designing-and-Implementing-Microsoft-Azure-Networking-Solutions#208]
# Module/LP: 08
#### Step: 02

Description of issue
Health probes don't support "Unhealthy threshold anymore", there is no field for that. Please remove from instructions.

### Relevant screenshots
![image](https://user-images.githubusercontent.com/37703728/228860902-4e2029a7-9471-44db-a3e1-c8140b19b58a.png)

**Comment by jileary23** [comment]
This has been updated
