### ISSUE TITLE
Lab 8 - UI changes in VM creation not reflected

### ISSUE THREAD

**Issue by mkennten** [MicrosoftLearning/AZ-700-Designing-and-Implementing-Microsoft-Azure-Networking-Solutions#209]
# Module: 08
#### Step: 04

Description of issue
UI has changed and there is no option "Place this virtual machine behind an existing load balancing solution?" anymore. It's now "Load balancing options: None", see screenshot

### Relevant screenshots
![image](https://user-images.githubusercontent.com/37703728/228867208-c3b03b90-5e2b-4105-a2c2-0d3e335210cb.png)

**Comment by jileary23** [comment]
This new setting is not consistent with every Azure portal experience. A note has been added to make students aware that the UI might be slightly different than the instructions, but the fundamental concept is the same.
