### ISSUE TITLE
M02-Unit 3 Create and configure a virtual network gateway - need to change to STANDARD SKU for Public IP

### ISSUE THREAD

**Issue by mkennten** [MicrosoftLearning/AZ-700-Designing-and-Implementing-Microsoft-Azure-Networking-Solutions#213]
This is regarding #204 since this issue has not been fixed yet.

Module: 02
Lab: M02 - Unit 3 Create and configure a virtual network gateway
Task: 06
Step: 03
Instructions tell us to select BASIC SKU for the VpnGw1 but only STANDARD is selectable - BASIC cannot be selected (anymore?). The deployment still works with Standard, instructions need to be updated.

### Relevant screenshots
<img width="460" alt="image" src="https://github.com/MicrosoftLearning/AZ-700-Designing-and-Implementing-Microsoft-Azure-Networking-Solutions/assets/37703728/332946bf-12fd-4d37-8fb0-665c3091cc3c">

**Comment by mkennten** [comment]
The SKU was changed for ManufacturingVnet not for CoreServicesVnet, this still must be done.

**Comment by jileary23** [comment]
updated
