### ISSUE TITLE
M06-Unit 4 - Unsupported Linux version deployed

### ISSUE THREAD

**Issue by mkennten** [MicrosoftLearning/AZ-700-Designing-and-Implementing-Microsoft-Azure-Networking-Solutions#216]
# Module: 06
#### Step: 03

Description of issue
Ubuntu Server 18.04 LTS should be selected which is out-of-support tomorrow. Should be changed to another supported version.

https://ubuntu.com/blog/18-04-end-of-standard-support

### Relevant screenshots
<img width="333" alt="image" src="https://github.com/MicrosoftLearning/AZ-700-Designing-and-Implementing-Microsoft-Azure-Networking-Solutions/assets/37703728/979e6ce7-50be-4fca-9dda-aed5b4d91b6b">

**Comment by eestevao1** [comment]
[like]  Elias Estevao reacted to your message:
________________________________
From: Michael Kenntenich ***@***.***>
Sent: Wednesday, May 31, 2023 7:46:33 AM
To: MicrosoftLearning/AZ-700-Designing-and-Implementing-Microsoft-Azure-Networking-Solutions ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [MicrosoftLearning/AZ-700-Designing-and-Implementing-Microsoft-Azure-Networking-Solutions] M06-Unit 4 - Unsupported Linux version deployed (Issue #216)


Module: 06
Lab: M06-Unit 4 Configure DDoS Protection on a virtual network using the Azure portal
Task: 06
Step: 03

Description of issue
Ubuntu Server 18.04 LTS should be selected which is out-of-support tomorrow. Should be changed to another supported version.

https://ubuntu.com/blog/18-04-end-of-standard-support

Relevant screenshots
[image]<https://user-images.githubusercontent.com/37703728/242198171-979e6ce7-50be-4fca-9dda-aed5b4d91b6b.png>
