### ISSUE TITLE
M06-Unit 4 Change of scope obsolete/UI changes required

### ISSUE THREAD

**Issue by mkennten** [MicrosoftLearning/AZ-700-Designing-and-Implementing-Microsoft-Azure-Networking-Solutions#217]
# Module: 06
#### Step: Configure DDoS alerts - 01-06

Description of issue
It doesn't make any sense to start with the DDoS Plan to configure an alert for the Public IP address (changing the scope for that very reason is obsolete). Other than that the UI has changed, and the instructions must be updated in several locations. So either you want for some reason to do it that way, then you need to update the UI element (no "Edit scope" anymore, "Conditions" looks different). Or you change this to the following approach.

This should instruct the learner to:
1. Select the Public IP address MyPublicIPAddress from the All Resources list
2. Click Alerts
3. Create a new alert rule
4. Select the signal "Under DDoS attack or not"
and from there continue with the configuration.

As an alternative, one could also start on the Alerts level and select the Public IP address from there.

**Comment by eestevao1** [comment]
[like]  Elias Estevao reacted to your message:
________________________________
From: Michael Kenntenich ***@***.***>
Sent: Wednesday, May 31, 2023 7:59:54 AM
To: MicrosoftLearning/AZ-700-Designing-and-Implementing-Microsoft-Azure-Networking-Solutions ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [MicrosoftLearning/AZ-700-Designing-and-Implementing-Microsoft-Azure-Networking-Solutions] M06-Unit 4 Change of scope obsolete/UI changes required (Issue #217)


Module: 06
Lab: M06-Unit 4 Configure DDoS Protection on a virtual network using the Azure portal
Task: 06
Step: Configure DDoS alerts - 01-06

Description of issue
It doesn't make any sense to start with the DDoS Plan to configure an alert for the Public IP address (changing the scope for that very reason is obsolete). Other than that the UI has changed, and the instructions must be updated in several locations. So either you want for some reason to do it that way, then you need to update the UI element (no "Edit scope" anymore, "Conditions" looks different). Or you change this to the following approach.

This should instruct the learner to:

  1.  Select the Public IP address MyPublicIPAddress from the All Resources list
  2.  Click Alerts
  3.  Create a new alert rule
  4.  Select the signal "Under DDoS attack or not"
and from there continue with the configuration.

As an alternative, one could also start on the Alerts level and select the Public IP address from there.

**Comment by jileary23** [comment]
This has been updated. Thank you.

**Comment by eestevao1** [comment]
[heart]         Elias Estevao reacted to your message:
________________________________
