### ISSUE TITLE
M08-Unit 3 Simplify VM deployment to shorten required lab time

### ISSUE THREAD

**Issue by mkennten** [MicrosoftLearning/AZ-700-Designing-and-Implementing-Microsoft-Azure-Networking-Solutions#218]
# Module: 08
### Task: 06 (Create backend servers)

Suggestions to speed up the lab and simplify steps:
1. To save time, the backend VMs could be created right after Task 1 (Create the virtual network) has been completed. While the deployment is processed, the Load Balancer can be configured and the Backendpool created or VMs added once they have been created.
2. Instead of running three separate deployments and ask every time for the adminPassword, the three VMs could be deployed with just one template like in AZ-104 (https://microsoftlearning.github.io/AZ-104-MicrosoftAzureAdministrator/Instructions/Labs/LAB_04-Implement_Virtual_Networking.html#task-2-deploy-virtual-machines-into-the-virtual-network), link to template: https://github.com/MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator/blob/master/Allfiles/Labs/04/az104-04-vms-loop-template.json

Currently, not only do I have to wait for the VMs to be deployed one by one but also, I need to wait in front of the prompt to see the password being requested.

**Comment by mkennten** [comment]
The solution to this issue can be applied to #219  as well.

**Comment by jileary23** [comment]
updated the ARM template to deploy the VMs together.

**Comment by eestevao1** [comment]
[like]  Elias Estevao reacted to your message:
________________________________

**Comment by eestevao1** [comment]
[like]  Elias Estevao reacted to your message:
________________________________
