### ISSUE TITLE
M04-Unit 4 Simplify VM deployment to shorten required lab time

### ISSUE THREAD

**Issue by mkennten** [MicrosoftLearning/AZ-700-Designing-and-Implementing-Microsoft-Azure-Networking-Solutions#219]
# Module: 04
### Task: 02 (Create backend servers)

Suggestion to speed up the lab and simplify steps:

- Instead of running three separate deployments and ask every time for the adminPassword, the three VMs could be deployed with just one template like in AZ-104 (https://microsoftlearning.github.io/AZ-104-MicrosoftAzureAdministrator/Instructions/Labs/LAB_04-Implement_Virtual_Networking.html#task-2-deploy-virtual-machines-into-the-virtual-network), link to template: https://github.com/MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator/blob/master/Allfiles/Labs/04/az104-04-vms-loop-template.json

Currently, not only do I have to wait for the VMs to be deployed one by one but also, I need to wait in front of the prompt to see the password being requested.

The solution to this issue can be applied to #218 as well.

**Comment by tumultuous1** [comment]
I am seeing the same thing, and it is frustrating having to run these deployments individually.  Can we expect an update on this any time soon?
