### ISSUE TITLE
M08-Unit 3 Consolidate IIS PowerShell lines into one script to copy and paste

### ISSUE THREAD

**Issue by mkennten** [MicrosoftLearning/AZ-700-Designing-and-Implementing-Microsoft-Azure-Networking-Solutions#220]
# Module: M08-Unit 3 Monitor a load balancer resource using Azure Monitor
#### Step: 08-10

Description of issue
To gain a better overview and avoid typing, the installation and configuration of the IIS should be shown as one PowerShell script that is easy to copy and paste like with other PowerShell lines.

```
Install-WindowsFeature -name Web-Server -IncludeManagementTools
Remove-Item C:\inetpub\wwwroot\iisstart.htm
Add-Content -Path "C:\inetpub\wwwroot\iisstart.htm" -Value $("Hello World from " + $env:computername)
```

To save time, this could also be part of the ARM template that creates the VMs.

**Comment by jileary23** [comment]
IIS install is part of the ARM template. Thank you.
