### ISSUE TITLE
M02-Lab - missing cloudshell instructions

### ISSUE THREAD

**Issue by athelen20** [MicrosoftLearning/AZ-700-Designing-and-Implementing-Microsoft-Azure-Networking-Solutions#221]
# Module: 02
### Task: 00

Description of issue
There is a need for the cloudshell but the cloudshell is not provisioned in the instructions - especially for LearnOnDemand.

Repro steps:
Add a note to create the cloudschell with the default settings.

**Comment by jileary23** [comment]
added instructions.
