### ISSUE TITLE
M04-Unit 4 - Change Bastion Subnet to /26 from /24

### ISSUE THREAD

**Issue by mkennten** [MicrosoftLearning/AZ-700-Designing-and-Implementing-Microsoft-Azure-Networking-Solutions#223]
# Module: M04
#### Step: 12

Description of issue
The UI for creating a VNET switches randomly currently between a "new" and "old" approach, which is causing confusion in some labs. In this one, the "new" UI doesn't allow you to configure the CIDR block to be /24, it will default to /26. One could change this in the subnet configuration, but I like the fact that it doesn't default to /24 because this would be unnecessary big. I'd like to suggest changing the instructions to use /26 for Bastion and that way both UI users have at least the same outcome.

### Relevant screenshots
![image](https://github.com/MicrosoftLearning/AZ-700-Designing-and-Implementing-Microsoft-Azure-Networking-Solutions/assets/37703728/d72a5856-2172-4612-9504-433f553397a3)

![image](https://github.com/MicrosoftLearning/AZ-700-Designing-and-Implementing-Microsoft-Azure-Networking-Solutions/assets/37703728/0d95f552-2ff5-4129-b9c8-d8c6a9fd907a)

**Comment by eestevao1** [comment]
[like]  Elias Estevao reacted to your message:
________________________________

**Comment by jileary23** [comment]
This has been fixed. Thank you.

**Comment by eestevao1** [comment]
[heart]         Elias Estevao reacted to your message:
________________________________
