### ISSUE TITLE
Update M07-Unit 5 NSG creation is missing a step

### ISSUE THREAD

**Issue by raboley** [MicrosoftLearning/AZ-700-Designing-and-Implementing-Microsoft-Azure-Networking-Solutions#224]
# Module: M07
#### Step: 02

Description of issue

The table describing how to create a NSG to block internet traffic is missing the source `Service Tag` attribute

Repro steps:

1. Try to create an NSG 
2. Try to select `Virtual Network` under Source and don't find it

### Relevant screenshots

   | **Setting**             | **Value**                 |
   | ----------------------- | ------------------------- |
   | Source                  | Select **VirtualNetwork** |

should be

   | **Setting**             | **Value**                 |
   | ----------------------- | ------------------------- |
   | Source                  | Select **Service Tag**    |
   | Source service tag      | Select **VirtualNetwork** |

**Comment by MSFT-mengchong** [comment]
@raboley Are you referring to the task where an inbound security rule is created to allow RDP connections?  https://microsoftlearning.github.io/AZ-700-Designing-and-Implementing-Microsoft-Azure-Networking-Solutions/Instructions/Exercises/M07-Unit%205%20Restrict%20network%20access%20to%20PaaS%20resources%20with%20virtual%20network%20service%20endpoints.html#task-5-allow-access-for-rdp-connections

![add-inbound-security-rule](https://github.com/MicrosoftLearning/AZ-700-Designing-and-Implementing-Microsoft-Azure-Networking-Solutions/assets/136421132/3ef00b7f-b3f1-47b6-bd76-18745d37bd9c)
