### ISSUE TITLE
M07 - Unit5 - Task 7: Create a file share in the storage account has changed and breaks deployment

### ISSUE THREAD

**Issue by kareldewinter** [MicrosoftLearning/AZ-700-Designing-and-Implementing-Microsoft-Azure-Networking-Solutions#227]
# Module: 07
#### Step: 02

Description of issue
**Create a file share in the storage account has changed. Default behavior creates a backup vault and breaks deployment due to Disallowed by Policy.** 

Repro steps:

1. Create File Share with default settings

### Relevant screenshots
<img width="1426" alt="new-file-share-denied" src="https://github.com/MicrosoftLearning/AZ-700-Designing-and-Implementing-Microsoft-Azure-Networking-Solutions/assets/40666689/70db7e1b-4239-4724-b454-f17574652eb4">

**Comment by eestevao1** [comment]
[heart]         Elias Estevao reacted to your message:
________________________________
