### ISSUE TITLE
VM template doesn't work in given resource group

### ISSUE THREAD

**Issue by maxJs1989** [MicrosoftLearning/AZ-700-Designing-and-Implementing-Microsoft-Azure-Networking-Solutions#229]
# Module: 02
#### Step: 03

Description of issue
when I try and create the VM I get the elow error message
New-AzResourceGroupDeployment: 5:53:40 PM - Error: Code=InvalidTemplateDeployment; Message=The template deployment failed with error: 'The resource with id: '/subscriptions/c50e464d-41fe-4b42-b1c3-d045521a8d6d/resourceGroups/ContosoResourceGroup/providers/Microsoft.Compute/virtualMachines/ManufacturingVM' failed validation with message: 'The requested size for resource '/subscriptions/c50e464d-41fe-4b42-b1c3-d045521a8d6d/resourceGroups/ContosoResourceGroup/providers/Microsoft.Compute/virtualMachines/ManufacturingVM' is currently not available in location 'West Europe' zones '' for subscription 'c50e464d-41fe-4b42-b1c3-d045521a8d6d'. Please try another size or deploy to a different location or zones. See https://aka.ms/azureskunotavailable for details.'.'.
New-AzResourceGroupDeployment: 5:53:40 PM - Error: Code=SkuNotAvailable; Message=The resource with id: '/subscriptions/c50e464d-41fe-4b42-b1c3-d045521a8d6d/resourceGroups/ContosoResourceGroup/providers/Microsoft.Compute/virtualMachines/ManufacturingVM' failed validation with message: 'The requested size for resource '/subscriptions/c50e464d-41fe-4b42-b1c3-d045521a8d6d/resourceGroups/ContosoResourceGroup/providers/Microsoft.Compute/virtualMachines/ManufacturingVM' is currently not available in location 'West Europe' zones '' for subscription 'c50e464d-41fe-4b42-b1c3-d045521a8d6d'. Please try another size or deploy to a different location or zones. See https://aka.ms/azureskunotavailable for details.'.
New-AzResourceGroupDeployment: The deployment validation failed
Repro steps:

### Relevant screenshots
![image](https://github.com/MicrosoftLearning/AZ-700-Designing-and-Implementing-Microsoft-Azure-Networking-Solutions/assets/148268939/af9fc9eb-567e-41ca-8874-aa488f9df2de)

**Comment by jileary23** [comment]
This issue is specific to your subscription. Edit the template locally to a VM SKU your subscription supports in the West Europe region.
