### ISSUE TITLE
Mod 1 - Unit 8 - Task 1 - Step 2 - Manufacturing VM creation fails. 

### ISSUE THREAD

**Issue by arnoldvilleneuve** [MicrosoftLearning/AZ-700-Designing-and-Implementing-Microsoft-Azure-Networking-Solutions#233]
# Module: 01
#### Step: 02

Description of issue

Manufacturing VM deployment fails with "wrong region" error on VM NIC creation. Both resources must be created in same region error message. 

![Mod1 Unit 8 Task 1 Step 2 Manufacturing VM deployment failes](https://github.com/MicrosoftLearning/AZ-700-Designing-and-Implementing-Microsoft-Azure-Networking-Solutions/assets/1082625/f5bd9396-b80b-4192-ba19-4680762272d6)

**Comment by arnoldvilleneuve** [comment]
Please note that as a result we could not finish this lab. Please fix it.

**Comment by NNifan** [comment]
Hi Lab 2, you have templates to create Virtual Networks. As Manufacturing VNets are being created in the North West, just deploy the Vnet and check the region. Then, you can continue with the LAP.

![image](https://github.com/MicrosoftLearning/AZ-700-Designing-and-Implementing-Microsoft-Azure-Networking-Solutions/assets/114994152/4e7ff18b-744d-4ab2-ac74-42293ad841ba)

**Comment by arnoldvilleneuve** [comment]
Fix the lab instructions.

**Comment by arnoldvilleneuve** [comment]
Please correct the lab instructions. 
As an Author you have to remember that many students are going to do these labs for the first time without an Instructor around to help them. The responsibility you accepted as the course Author is to keep it up to date. 
Arnold Villeneuve 613-833-0984 

    On Wednesday, February 14, 2024 at 11:04:04 a.m. EST, Jill Leary ***@***.***> wrote:  
 
 


Closed #233 as completed.
