### ISSUE TITLE
Almost every lab has some kind of issue(s)

### ISSUE THREAD

**Issue by arnoldvilleneuve** [MicrosoftLearning/AZ-700-Designing-and-Implementing-Microsoft-Azure-Networking-Solutions#235]
Small things but annoying nonetheless. Almost every lab has instructions that are not fully accurate, the "Edit Button" no longer exists, the example screenshot is not correct,  etc, etc, etc. I literally had to be involved helping students figure out workarounds for every lab. Like I said, sometimes small stuff but still wrong and demonstrating that the lab instructions are not being kept up to date!

**Comment by NNifan** [comment]
"I partially agree with you. While there may be some mistakes, Azure regularly updates its UI. Therefore, this module may have missed some of the newer updates. If you are still experiencing issues, please let me know and I will try to guide you."

**Comment by arnoldvilleneuve** [comment]
I do not require guidance. Please keep the course up to date. That is the author's responsibility and what Learning Partners and Instructors expect. 
Arnold Villeneuve 613-833-0984 

    On Wednesday, January 31, 2024 at 11:22:42 a.m. EST, NNifan ***@***.***> wrote:  
 
 


"I partially agree with you. While there may be some mistakes, Azure regularly updates its UI. Therefore, this module may have missed some of the newer updates. If you are still experiencing issues, please let me know and I will try to guide you."
