### ISSUE TITLE
LP 04, Task 5, Creating the test VM doesn't have the same listed size available in the instructions

### ISSUE THREAD

**Issue by SkillableBB** [MicrosoftLearning/AZ-700-Designing-and-Implementing-Microsoft-Azure-Networking-Solutions#236]
In LP 05, Task 5, the user is instructed to create a test VM with the size Standard_DS1_v2 - 2 vcpu, 8 GiB memory [p1]. This size is no longer showing as available in Azure [p2].

 I was able to successfully create it using the DS1v2 VM size with 1vpcu and 3.5GiB memory, but I'm not sure if that's the specifications that is wanted, it's more important that the written size is no longer showing as available in the Azure portal.

[p1]

![image](https://github.com/MicrosoftLearning/AZ-700-Designing-and-Implementing-Microsoft-Azure-Networking-Solutions/assets/94069201/c06c41d0-2f04-44d5-b069-9d4af7ab46f6)

[p2]

![image-1](https://github.com/MicrosoftLearning/AZ-700-Designing-and-Implementing-Microsoft-Azure-Networking-Solutions/assets/94069201/28d90f0e-586f-41bc-a5a4-6081cdd2c6b4)

**Comment by jileary23** [comment]
This is specific to a lab hosting environment not all Azure subscriptions have this restriction. I will update the lab hosted environment.
