### ISSUE TITLE
big issue with json file HELP

### ISSUE THREAD

**Issue by mctfabrice** [MicrosoftLearning/AZ-700-Designing-and-Implementing-Microsoft-Azure-Networking-Solutions#237]
Hello
**BIG BIG Issue**
**the JSON template don't WORK**

Student has to create manually the vm or change the json file
They are flustered and feedback is no good at all !!!

for the lab on peering
and local virtual network gateway

The location of the resource group is in east us
and the vnet are in others region

In the lab on creating vnet to vnet with local virtual network gateway 
when we have to create the connexions no shared key option 

please help

**Comment by jileary23** [comment]
Can you please provide specifics on which json template the student had to change in order to get it to work? Please also provide the error shown when the original template didnt work and the lab hoster that was being used. This might be a lab hosting environment blocker.
