### ISSUE TITLE
Multiple Modules - Cloud Shell provisioning instructions incorrect

### ISSUE THREAD

**Issue by MSFT-lamatthe** [MicrosoftLearning/AZ-700-Designing-and-Implementing-Microsoft-Azure-Networking-Solutions#240]
# Module: Multiple (M01, M02, M03, M04, M05, M06, M07, M08)
#### Step: 00

Description of issue:
Instructions for Cloud Shell provisioning in all modules currently read:

1. On the Azure portal, open the **PowerShell** session within the **Cloud Shell** pane.
 > **Note:** If this is the first time opening Cloud Shell, you might be prompted to create a storage account. Select **Create storage**.

Steps actually required listed below, presuming a persistent storage account is required.

Repro steps:

1. Open **Cloud Shell** prompt
2. Select **PowerShell**
3. Select **Mount Storage Account** then **Apply**
4. Select **We will create a storage account for you** then **Next**

### Relevant screenshots
![Screenshot 2024-08-19 141603](https://github.com/user-attachments/assets/8574bbb8-8438-404c-87c8-61032bd45127)
![Screenshot 2024-08-19 141627](https://github.com/user-attachments/assets/8b5cee57-3196-49d0-91ef-c192121babae)
![Screenshot 2024-08-19 141643](https://github.com/user-attachments/assets/f2f390cc-1afa-433e-8008-9c54ad0ad729)

**Comment by staleycyn** [comment]
Made some corrections. If I missed one, write back.
