### ISSUE TITLE
Module 02, Unit 03 - Instructions Clarity required

### ISSUE THREAD

**Issue by MSFT-lamatthe** [MicrosoftLearning/AZ-700-Designing-and-Implementing-Microsoft-Azure-Networking-Solutions#242]
# Module: 02
#### Step: 01

Description of issue
When searching for "Connections" in the portal, two products are now visible instead of one:
- Connections (Microsoft.AzureDataTransfer); and
- Connections (Microsoft.Network)
There's no way to distinguish which is the "right" one without a visual cue or by instead verifying the connections via the steps in Task 11

Repro steps:

1. **Search resources, services, and docs (G+/)**, enter **connections**

### Relevant screenshots
![Screenshot 2024-08-19 152810](https://github.com/user-attachments/assets/937fc25f-f135-4f78-af29-c6ab261f88ae)

**Comment by staleycyn** [comment]
made a correction. write back if there is still and issue.
