### ISSUE TITLE
M05-Unit 6 Create a Front Door for a highly available web application using the Azure portal

### ISSUE THREAD

**Issue by SkillableBB** [MicrosoftLearning/AZ-700-Designing-and-Implementing-Microsoft-Azure-Networking-Solutions#244]
M05-Unit 6, Task 2: Create a Front Door for your application

 If you follow the directions as written selecting Quick Create you receive a policy violation as displayed in the Frontdoorerror2 file.  

If you select Explore other offers as suggested above the instructions - in the Notes section -  and select Azure Front Door (classic) you must register the CDN service in the subscription and you receive the error displayed in the frontdoor file.  

If you assume the instructions are incorrect, and select Explore other offerings, and then select Azure CDN Standard from Microsoft (classic) the lab works, just not as written.  The last option does not have all the selections that are noted in the lab, but it demonstrates a working product.  

### Relevant screenshots

![image](https://github.com/user-attachments/assets/7866232e-e656-425d-8f83-5e50b8745512)

**Comment by staleycyn** [comment]
This has been fixed. Thanks Skillable.
