### ISSUE TITLE
Changes in GUI

### ISSUE THREAD

**Issue by TommyKobber** [MicrosoftLearning/AZ-700-Designing-and-Implementing-Microsoft-Azure-Networking-Solutions#248]
# Module: 01
#### Step: 04

Description of issue
The GUI has changed in many ways. The top of the potal shows the remote network, the bottom shows the local network. The text has also changed

Remote virtual network summary  |  
  | Peering link name | ManufacturingVnet-to-CoreServicesVnet
  | Virtual network deployment model | Resource manager
  | Virtual network | ManufacturingVnet
Remote virtual network peering settings
Allow 'ManufacturingVnet' to access 'CoreServicesVnet' | Yes
Allow 'ManufacturingVnet' to receive forwarded traffic from 'CoreServicesVnet' | Yes
 
Local virtual network summary |   |  
  | Peering link name | CoreServicesVnet-to-ManufacturingVnet
  
 Remote virtual network peering settings 
  | Allow 'CoreServicesVnet' to access 'ManufacturingVnet' | Yes
  | Allow 'CoreServicesVnet' to receive forwarded traffic from 'ManufacturingVnet' | Yes
 
Review your settings and select Add.

**Comment by staleycyn** [comment]
Corrected.
