### ISSUE TITLE
Error in templates and suggestion for update of lab step

### ISSUE THREAD

**Issue by TommyKobber** [MicrosoftLearning/AZ-700-Designing-and-Implementing-Microsoft-Azure-Networking-Solutions#249]
# Module: 02
#### Step: 02 in Task 1, step 3 in tasks 6 and 7

Task 1 step 2: The azuredeploy.json doesn't have info on GatewaySubnet for ManufacturingVnet, only CoreServicesVnet.

Task 6 and 7: The VPN gateways are deployed as VPNGw1 Sku's, Gen1. After January 1st 2025 this will not be possible, according to this: [https://azure.microsoft.com/da-dk/updates/v2/vpngw1-5-non-az-skus-will-be-retired-on-30-september-2026/]
So this should be changed to an AZ SKU 

Repro steps:

1.
1.

**Comment by staleycyn** [comment]
Added steps to manually create the Manufacturing GatewaySubnet. We will wait on changing the gateway SKU. This requires a lab hoster policy change.
