### ISSUE TITLE
M05-Unit 6 - Microsoft.Cdn Resource Provider is not registered by default

### ISSUE THREAD

**Issue by SkillableJM** [MicrosoftLearning/AZ-700-Designing-and-Implementing-Microsoft-Azure-Networking-Solutions#252]
# Module: 05 - Unit 6 Create a Front Door for a highly available web application using the Azure portal
#### Step: 3

<ins>Description of issue</ins>
Users are unable to create the Front Door without first registering the Microsoft.Cdn resource provider. Skillable has added an LCA to automatically register the Microsoft.Cdn resource provider, but this may still be affecting other ALH's.

Workaround can be found here: https://learn.microsoft.com/en-us/azure/azure-resource-manager/management/resource-providers-and-types?WT.mc_id=Portal-Microsoft_Azure_AFDX

### Relevant screenshots
![image](https://github.com/user-attachments/assets/bf5d19ca-f1bd-4291-b05d-fdb2249e2a43)
![image](https://github.com/user-attachments/assets/d9cd79c2-de35-4577-ba37-7732bc6590e0)

**Comment by staleycyn** [comment]
This was previously reported and closed - https://github.com/MicrosoftLearning/AZ-700-Designing-and-Implementing-Microsoft-Azure-Networking-Solutions/issues/244 

Is there something else that needs to be done?

**Comment by SkillableJM** [comment]
I believe this is slightly different, as #244 required the user to register Cdn if using the Azure Front Door (classic) version. This issue is now occurring when creating the Front Door using the Quick create option as well. There is no mention of registering the Cdn resource provider within the instructions, but it must be registered in order for the user to create the Front Door. 

Skillable added an LCA to automatically register the resource provider upon lab launch, but wanted to bring awareness to this matter should other ALH/training partners run into this.

![image](https://github.com/user-attachments/assets/d11d554d-8448-4171-adea-39f86f63b545)
