### ISSUE TITLE
Creation of VMs should be part of ARM Templates used for lab setup

### ISSUE THREAD

**Issue by PaulDash** [MicrosoftLearning/AZ-700-Designing-and-Implementing-Microsoft-Azure-Networking-Solutions#36]
# Module: 02
### Task: 02 and 03

Creation of the VMs used for testing connectivity should be part of ARM Templates used for lab setup

It's wasteful to have students enter details to create VMs during the lab exercises instead of concentrating on the networking. Especially in a place like Module 2, Unit 3, where a lot of time is spent waiting for the VPN Gateways to create. The VM creation should be a part of the ARM Templates that are used to set up other objects for lab setup.

**Comment by jileary23** [comment]
Thank you for your feedback. Please check back on or before Feb 11, 2022 for this change.
