### ISSUE TITLE
M01 - Unit 6 Configure DNS settings in azure

### ISSUE THREAD

**Issue by azharkhuwaja** [MicrosoftLearning/AZ-700-Designing-and-Implementing-Microsoft-Azure-Networking-Solutions#38]
# Module: M01 - Unit 6 Configure DNS settings in azure
#### Step: 11 and 12

Description of issue: wrong password mentioned in steps 11 and 12.

Please change the value of passwords in steps 11 and 12 to **TestPa$$w0rd!**

**Comment by MOC-Labs-Review** [comment]
MOC-Labs-Review has resolved this issue with PR #52
