### ISSUE TITLE
M01 - Unit 6 Configure DNS settings in azure

### ISSUE THREAD

**Issue by azharkhuwaja** [MicrosoftLearning/AZ-700-Designing-and-Implementing-Microsoft-Azure-Networking-Solutions#39]
# Module: M01 - Unit 6 Configure DNS settings in azure
#### Step: 18

Description of issue: In order to see successful Ping, I had to turn off Microsoft Defender Firewall under Local Server of both virtual machines. Kindly add a comment in step 18 about turning off Microsoft Defender Firewall.

**Comment by jileary23** [comment]
Thank you for your feedback. This lab has been updated
