### ISSUE TITLE
M01 - Unit 6

### ISSUE THREAD

**Issue by azharkhuwaja** [MicrosoftLearning/AZ-700-Designing-and-Implementing-Microsoft-Azure-Networking-Solutions#42]
# Module: M01 - Unit 6
#### Step: 18

Description of issue: Please add a comment at the end that **you can now terminate both RDP sessions before proceeding to the next lab**. There are two active RDP sessions connecting to TestVM1 and TestVM2 virtual machines. Thanks

**Comment by jileary23** [comment]
Thank you for your feedback.
