### ISSUE TITLE
Module: M02-Unit 3

### ISSUE THREAD

**Issue by azharkhuwaja** [MicrosoftLearning/AZ-700-Designing-and-Implementing-Microsoft-Azure-Networking-Solutions#44]
# Module: Module: M02-Unit 3
#### Step: 03

Description of issue: We cleaned up VNET and Subnet resources at the end of previous module. Therefore please change following table values:

Networking | Virtual network | **CoreServicesVnet**

Subnet | **DatabaseSubnet (10.20.20.0/24)**

Changed values can be:

Networking | Virtual network | **(new) CoreServicesVnet (10.20.0.0/16)**

Subnet | **(new) DatabaseSubnet (10.20.20.0/24)**

**Comment by MOC-Labs-Review** [comment]
MOC Labs Review confirms this issue and has submitted PR #55
