### ISSUE TITLE
M01 Unit 6 Task 4 - Password specified doesn't match password set previously in lab.

### ISSUE THREAD

**Issue by DurhamNeil** [MicrosoftLearning/AZ-700-Designing-and-Implementing-Microsoft-Azure-Networking-Solutions#51]
# Module: 01
#### Step: 00

Description of issue
Password in step 4 doesn't match password set previously in Task 3 (It's missing a $ sign)

Repro steps:

1. Alter password in 'Connect to the test VMs using RDP' from TestPa$w0rd! to TestPa$$w0rd!

**Comment by jileary23** [comment]
Thank you for your feedback this was fixed in a previous pull request.
