### ISSUE TITLE
Exercise M02

### ISSUE THREAD

**Issue by athelen20** [MicrosoftLearning/AZ-700-Designing-and-Implementing-Microsoft-Azure-Networking-Solutions#64]
# Module: 02
#### Step: 00

Description of issue
The CoreServicesVnet created with the azuredeploy.json file is created in the East US - the next task however asks us to add a VM in the West US to that Vnet.

Repro steps:
Either
Update azuredeploy.json (line 24) to westus
OR
Change the instructions in Task 2 to create the VM in the East US

**Comment by athelen20** [comment]
Issue continues with the ManufacturingVnet - template deploys it in West Europe and instructions read to create the VM in (Europe) North Europe

And then the Gateways need to also be created in "correctly named region"

**Comment by jileary23** [comment]
Thank you for your feedback this was fixed in a previous pull request.
