### ISSUE TITLE
Module 4, task 4 Error - Lab could be completed. 

### ISSUE THREAD

**Issue by arnoldvilleneuve** [MicrosoftLearning/AZ-700-Designing-and-Implementing-Microsoft-Azure-Networking-Solutions#74]
# Module: 04
#### Step: 01

Description of issue
Here is the error I am getting with Module 4, task 4. We are supposed to copy and paste the DNS from the Traffic Manager Profile into a new browser tab, but when I do that, I get this error.

Repro steps:

This is what we are supposed to be getting, but this is not what I am getting.

Images of error attached. All Students, including myself as Instructor encountered the same issue. 

Lab could not be comspleted. 
![AZ-700-Mod4-Lab-Continued](https://user-images.githubusercontent.com/1082625/150445822-44a96181-b199-4e0f-a08e-13ce03bd8228.png)
![AZ-700-Mod4-Lab](https://user-images.githubusercontent.com/1082625/150445823-60aaa68a-9839-434b-b2b2-da4f3c1e2357.png)

Instructor Comment: I see the following issues throughout the labs in this course and others when Cloud Slice Subscriptions are used. 

1. The Azure Polices that have been put for the Subscription and Management Groups are not allowing the Students to complete the labs as described. 

2. There are issues and confusion with which Regions Azures object (App, VM, Loadbalancer, etc) should be installed into thus also leading to failed lab completion. 

Some of the issues with this course that were raised back in November 2021 have still not been addressed by the Owners of this course.

**Comment by MOC-Labs-Review** [comment]
MOC Labs Review has solved this issue with pull request #116

**Comment by azharkhuwaja** [comment]
what is the solution of above issue? I tried today and faced same issue (not using cloud slice or any restricted subscription).
