### ISSUE TITLE
Mod05 - Traffic Manager Lab Could Not Be Completed

### ISSUE THREAD

**Issue by arnoldvilleneuve** [MicrosoftLearning/AZ-700-Designing-and-Implementing-Microsoft-Azure-Networking-Solutions#75]
# Module: 05
#### Step: 01

Description of issue
DNS Errors encountered by all students when doing the Traffic Manager section of the lab. Instructor encountered same issues. Lab could not be completed. 

Repro steps:

1. There are issues with the Azure Polices that are restricting the Cloud Slice Subscription from allowing the required task steps to be undertaken by the Students / Instructor. 

2. The DNS configuration steps are certainly wrong. We spent time trying to find a resolution but were unsuccessful.

**Comment by MOC-Labs-Review** [comment]
MOC Labs Review did not experience this issue.
