### ISSUE TITLE
M06-Unit 4 Configure DDoS Protection on a virtual network using the Azure portal - Breakingpoint.cloud DDOS attack does not work

### ISSUE THREAD

**Issue by arnoldvilleneuve** [MicrosoftLearning/AZ-700-Designing-and-Implementing-Microsoft-Azure-Networking-Solutions#76]
# Module: 06
#### Step: 01 Create an account with https://breakingpoint.cloud/

Description of issue
IP was not found in any valid subscription. 

Repro steps:
![AZ700-Mod6-Unit4-Task7-2](https://user-images.githubusercontent.com/1082625/150555936-509f7931-ee7f-4919-b91f-7e4e2a1bf4cf.png)
![AZ700-Mod6-Unit4-Task7-1](https://user-images.githubusercontent.com/1082625/150555938-296605c3-4749-4651-a122-2ffae3d1a0fa.png)

**Comment by JeffSmalley** [comment]
I was successful in running the BreakingPiont test but I had to use the 100k pps test size as mentioned in the step as maybe required. My Public IP Metric and my Alert worked but took along time for it to show up.  

I don't think it would matter but you used Port 80 and the lab was showing Port 443. I would guess that is not relevant. 

The problem with using BreakingPoint is with one test run, my trial account is over. I can't try it a second time. 

Jeff Smalley

![Capture6](https://user-images.githubusercontent.com/16696370/150654312-9f1cd9fa-42a7-4d62-a435-eceb444a57f6.PNG)

**Comment by arnoldvilleneuve** [comment]
Thank you for finding a solution Jeff. It is unfortunate the course has to depend on outside trial services like this. I had similar problems with access to outside trial services with the AZ-400 course.  
Arnold Villeneuve 613-833-0984 

    On Saturday, January 22, 2022, 03:29:56 p.m. EST, JeffSmalley ***@***.***> wrote:  
 
 


I was successful in running the BreakingPiont test but I had to use the 100k pps test size as mentioned in the step as maybe required. My Public IP Metric and my Alert worked but took along time for it to show up.

I don't think it would matter but you used Port 80 and the lab was showing Port 443. I would guess that is not relevant.

The problem with using BreakingPoint is with one test run, my trial account is over. I can't try it a second time.

Jeff Smalley



—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by MOC-Labs-Review** [comment]
MOC Labs Review did not experience this issue.
