### ISSUE TITLE
M06-Unit 7 Deploy and configure Azure Firewall using the Azure portal - Task 3 - Create Virtual Machine

### ISSUE THREAD

**Issue by arnoldvilleneuve** [MicrosoftLearning/AZ-700-Designing-and-Implementing-Microsoft-Azure-Networking-Solutions#77]
# Module: 06
#### Step: 03

Description of issue

Step 3: Size | Standard_D2s_v3 - 2vcpus, 8GiB memory - is not available due to policy. Only the B1s size VM is. Later in the lab the screenshot shows the B1s size as the one that was selected. 
![AZ700-Mod6-Unit7-Task3-1](https://user-images.githubusercontent.com/1082625/150558127-82535a15-d0cf-4a80-b675-21570c9a6042.png)
 

Repro steps:
Update Step 03.

**Comment by JeffSmalley** [comment]
I had no issues with this. I am guessing you may have an old Policy from another demo or lab still there preventing it.   I am using Central US. Maybe your region (UK South) is restricted for some reason.

Jeff Smalley  MCT

**Comment by arnoldvilleneuve** [comment]
I always try to use East US because it seems to be the one that works the most often. We tried Europe Central and UK South - neither worked. 
Arnold Villeneuve 613-833-0984 

    On Saturday, January 22, 2022, 05:32:01 p.m. EST, JeffSmalley ***@***.***> wrote:  
 
 


I had no issues with this. I am guessing you may have an old Policy from another demo or lab still there preventing it. I am using Central US. Maybe your region (UK South) is restricted for some reason.

Jeff Smalley MCT

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by MOC-Labs-Review** [comment]
MOC Labs Review did not experience this issue.

**Comment by arnoldvilleneuve** [comment]
Jill 
I see that you have closed a lot of these issues. Could you please share with us what you did to address all of the problems with this labs? 
Thank you. 
Arnold Villeneuve 613-833-0984 

    On Friday, April 1, 2022, 05:03:28 p.m. EDT, Jill Leary ***@***.***> wrote:  
 
 


Closed #77.
