### ISSUE TITLE
M06-Unit 9 Secure your virtual hub using Azure Firewall Manager - Resource Group already exists

### ISSUE THREAD

**Issue by arnoldvilleneuve** [MicrosoftLearning/AZ-700-Designing-and-Implementing-Microsoft-Azure-Networking-Solutions#78]
# Module: 06
#### Step: 03

Description of issue
Resource Group fw-manager-rglod21210188 already exists. 

Repro steps:
3. In Resource group, select Create new, and enter fw-manager-rglod21210188 as the name and click OK.

**Comment by DynamicChipmunk** [comment]
It looks like from the Resource Group name mentioned that this is a resource group that is pre-created by an ALH at the start of a lab.  Different hosters may approach this problem in different ways but often what you will find is a 'Note' at the beginning of such a lab with some clarifications to the student that RGs have already been created, and that they can select 'a pre-existing resource group that has a similar name to the one you are asked to create'.

So in this case - where the generic name in the repo is  'fw-manager-rg' you would be able to select the existing 'fw-manager-rglod21210188' RG that gets created at lab start.

**Comment by JeffSmalley** [comment]
I am not sure what the problem is here. If you delete all prior labs, you should not have an issue with a name conflict. Also, the Resource Group should just be named: fw-manager-rg.  I had no problems with this part of the lab.

Jeff Smalley MCT

**Comment by arnoldvilleneuve** [comment]
The resource in question is at the very start of the first lab unit. No previous Resource Groups were created. I do the labs with all the students at the same time. We all ran into the same issue. 
Arnold Villeneuve 613-833-0984 

    On Sunday, January 23, 2022, 05:14:12 p.m. EST, JeffSmalley ***@***.***> wrote:  
 
 


I am not sure what the problem is here. If you delete all prior labs, you should not have an issue with a name conflict. Also, the Resource Group should just be named: fw-manager-rg. I had no problems with this part of the lab.

Jeff Smalley MCT

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by JeffSmalley** [comment]
It looks like there is an issue, at least with me, in deleting the Resource Group fw-manager-rg.   The PowerShell script at the end of this lab does NOT delete the Virtual WAN, Firewall Manager nor the policy.   I had to go to the policy and open Hub-01 and go to Security Configurations. I then had to switch the Internet Traffic to **None** and the Private Traffic to **Bypass Azure Firewall** and Save.  That took over 10 minutes to complete.  Finally, I deleted the Resource Group fw-manager-rg and after over 10 minutes it worked.
![delete3](https://user-images.githubusercontent.com/16696370/150720364-d0d31c60-1ffc-4a70-a797-3cae8ac4ebd4.png)

Jeff Smalley MCT
Village of Chicago

**Comment by arnoldvilleneuve** [comment]
Great find Jeff. We'll done.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by JeffSmalley** [comment]
I had thoughts on some of you folks getting duplicate name issues. My class this week is using the Azure Pass so each student will have their own subscription as well as tenant. It will be all clean.  If you are using a lab provider like Learn On Demand, Skillable, etc. that use a communal account such as cloudslice, the problem with duplicate names is with their system providing random names for your resource groups, etc. not the lab itself.  The lab provider organization needs to be contacted I would think.  

Jeff

**Comment by arnoldvilleneuve** [comment]
Ahhh, mine was using Cloud Slice where you do not have enough Admin power to change policies. The deployment of Azure Policies with Cloud Slice subscriptions causing labs to fail has become a major issue across many Azure courses unfortunately. 
Arnold Villeneuve 613-833-0984 

    On Monday, January 24, 2022, 08:47:41 a.m. EST, JeffSmalley ***@***.***> wrote:  
 
 


I had thoughts on some of you folks getting duplicate name issues. My class this week is using the Azure Pass so each student will have their own subscription as well as tenant. It will be all clean. If you are using a lab provider like Learn On Demand, Skillable, etc. that use a communal account such as cloudslice, the problem with duplicate names is with their system providing random names for your resource groups, etc. not the lab itself. The lab provider organization needs to be contacted I would think.

Jeff

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by MOC-Labs-Review** [comment]
MOC Labs Review did not experience this issue.
