### ISSUE TITLE
M06-Unit 7 Deploy and configure Azure Firewall using the Azure portal

### ISSUE THREAD

**Issue by arnoldvilleneuve** [MicrosoftLearning/AZ-700-Designing-and-Implementing-Microsoft-Azure-Networking-Solutions#79]
# Module: 07
#### Step: 05

Description of issue
Azure Policy does not allow the creation of VM

Repro steps:
5. Select Create to start the virtual machine deployment. The VM takes a few minutes to deploy, but you can continue to the next step while the VM is creating.

Results in Policy Violation error. 
![AZ700-Mod7-Unit5-Task9-Step5](https://user-images.githubusercontent.com/1082625/150593760-68c89402-d570-41b1-a09c-acd2d07d88c8.png)

**Comment by JeffSmalley** [comment]
I had no issues with this. I am guessing you may have an old policy created from another lab.

Jeff

**Comment by arnoldvilleneuve** [comment]
Jeffrey
My understanding is that each lab is separate and independent of the others. Please correct me if I am wrong. I made a point of having students always first look at Resources Groups to see what was there or not there before we started the lab. 
You can't have five people go through this lab and all have the same issues Jeffrey. I sincerely that the time I have spent raising these lab issues are being taken seriously. 
Arnold Villeneuve 613-833-0984 

    On Sunday, January 23, 2022, 05:24:45 p.m. EST, JeffSmalley ***@***.***> wrote:  
 
 


I had no issues with this. I am guessing you may have an old policy created from another lab.

Jeff

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by MOC-Labs-Review** [comment]
MOC Labs Review did not experience this issue.
