### ISSUE TITLE
M06-Unit 9 Task 5: Create a firewall policy and secure your hub

### ISSUE THREAD

**Issue by JeffSmalley** [MicrosoftLearning/AZ-700-Designing-and-Implementing-Microsoft-Azure-Networking-Solutions#80]
# Module: 06
#### Step: 05

Description of issue

Repro steps:

Add a step after Step 6:
Set Policy tier to Standard.

It defaults to Premium which will cause an error later with assigning it.

Cheers,
Jeff Smalley MCT

**Comment by MOC-Labs-Review** [comment]
MOC Labs Review did not experience this issue.
