### ISSUE TITLE
Module 6 Unit 9 Task 4: Deploy the servers- No Size Listed

### ISSUE THREAD

**Issue by JeffSmalley** [MicrosoftLearning/AZ-700-Designing-and-Implementing-Microsoft-Azure-Networking-Solutions#81]
# Module: 06
#### Step: 03

Description of issue
For the creation of the 2 Virtual Machines. it does not list a Size. I would suggest: Standard_D2s_v3 - 2vcpus, 8GiB memory
If the size is too small, it causes delay issues trying to Remote Desktop into them. 

Cheers.
Jeff Smalley MCT

**Comment by MOC-Labs-Review** [comment]
MOC Labs Review did not experience this issue.
