### ISSUE TITLE
Module 6 Lab Unit 7 Task 4 Typo for Name of Firewall

### ISSUE THREAD

**Issue by JeffSmalley** [MicrosoftLearning/AZ-700-Designing-and-Implementing-Microsoft-Azure-Networking-Solutions#82]
# Module: 06
#### Step: 3

Description of issue
When creating a Firewall resource, it states “Virtual Machine Name” when it should just be “Name”

Cheers,
Jeff Smalley MCT
Chicagoville

**Comment by MOC-Labs-Review** [comment]
MOC Labs Review did not experience this issue.
