### ISSUE TITLE
Module 6 Unit 4 Lab Task 6 - Alert Steps

### ISSUE THREAD

**Issue by JeffSmalley** [MicrosoftLearning/AZ-700-Designing-and-Implementing-Microsoft-Azure-Networking-Solutions#83]
# Module: 06
#### Step: 2

Description of issue
It has us select the DDoS protection plan to begin the steps to do the Alert.  Selecting the **Public IP** resource  MyPublicIPAddress would make more sense since the Scope would already be set. Less Steps and more a practical way. 

Also, it looks like the creation of an Alert interface has changed. The steps will need to be updated slightly. 
Step 13 Needs to say: Click on Details Section....
![Alert Picture](https://user-images.githubusercontent.com/16696370/150701019-36cd6abe-986d-4be6-9702-927b2ccc1cae.PNG)

**Comment by MOC-Labs-Review** [comment]
MOC Labs Review did not experience this issue.

**Comment by azharkhuwaja** [comment]
I agree. step 13 statement is bit confusing right now.

**Comment by jileary23** [comment]
Thank you for your feedback.
