### ISSUE TITLE
Module 8 Unit 3 myNSG doesn't appear when creating VM

### ISSUE THREAD

**Issue by JeffSmalley** [MicrosoftLearning/AZ-700-Designing-and-Implementing-Microsoft-Azure-Networking-Solutions#84]
# Module: 8
#### Step: Create the Test VM section, Step 4:

Description of issue
We should NOT be setting the MyNSG to the Test VM since we have a Bastion Server setup for the VNET. When creating the VM we should set the NIC network security group to **None**.   

If you do still want the MyNSG applied I had the following issue:
On the Networking tab, the MyNSG does not show, I just set the NIC network security group to Basic. Turn on Public inbound ports and Select Inbound Port to be 3389. That is all the MyNSG does anyways.    The MyNSG does get deployed via the ARM templates and the MyNSG and the Test Virtual Machine are both set to West US. I am not sure why the ARM Template deployment has this issue of not showing when creating the Virtual Machine. This is similar to Module 2 Unit 3 issues with the CoreServicesVnet is not showing during the VM creation and also in Module 4 Unit 4 with the MyNSG resource hiding from the VM Creation there.  Very strange. 

Good Luck,
Jeff Smalley

**Comment by MOC-Labs-Review** [comment]
MOC-Labs-Review did not experience this Issue.
