### ISSUE TITLE
Module 3 Unit 5 - Formatting issue with Channel 9 link

### ISSUE THREAD

**Issue by MSFT-MarcoEs** [MicrosoftLearning/AZ-700-Designing-and-Implementing-Microsoft-Azure-Networking-Solutions#93]
# Module: 3
#### Step: 0

Description of issue: There is a formatting issue due to the use of pipes in link

Repro steps:
1. Remove the pipes from Azure ExpressRoute - How to create an ExpressRoute circuit | Azure | Channel 9 (msdn.com)

**Comment by MOC-Labs-Review** [comment]
MOC Labs Review did not experience this issue.
