### ISSUE TITLE
Module 4 Unit 6 - Removal of Contoso-RG-TM2 is missing

### ISSUE THREAD

**Issue by MSFT-MarcoEs** [MicrosoftLearning/AZ-700-Designing-and-Implementing-Microsoft-Azure-Networking-Solutions#95]
# Module: 4
#### Step: 2

Description of issue: Removal of Contoso-RG-TM2 is missing, only Contoso-RG-TM1 is listed whereas Contoso-RG-TM2 is also created during the lab.

Repro steps:
1. Contoso-RG-TM2 is created in Task 1 Step 7 and not deleted in Task 5 Step 2

**Comment by MOC-Labs-Review** [comment]
MOC Labs review has solved this issue with pull request #117
